#
# Service Accounts.
# https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
#

{
  "apiVersion": "v1",
  "kind": "ServiceAccount",
  "metadata": {
    "name": "mobile-app"
  }
}

---

{
  "apiVersion": "v1",
  "kind": "Secret",
  "metadata": {
    "name": "mobile-app-secret",
    "annotations": {
      "kubernetes.io/service-account.name": "mobile-app"
    }
  },
  "type": "kubernetes.io/service-account-token"
}
