#
# https://medium.com/@patrickeasters/using-traefik-with-tls-on-kubernetes-cb67fb43a948
# https://docs.traefik.io/toml
#

# https://docs.traefik.io/toml/#entrypoints-definition

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
