#
# Traefik Proxy Deployment and Service
# https://medium.com/@alex__richards/getting-started-with-traefik-43fb7302b224
# https://medium.com/@patrickeasters/using-traefik-with-tls-on-kubernetes-cb67fb43a948
# https://docs.traefik.io/user-guide/kubernetes
#
# The Service's Container has two processes:
#   traefik-proxy   (:80      => 443)
#   traefik-ui      (:8080    => 80)
#
# And references the SSL Cert via an annotation.
#   kubectl apply -f ./conf/k8s/traefik.yml
#
# Get the ELB's IP (LoadBalancer Ingress):
#   kubectl describe service traefik-proxy | sed -n 's/^LoadBalancer Ingress:.\(.*\)/\1/p'
#
# Then configure DNS (e.g., www CNAME a59e5a2b1278911e7be8c0e9a1a6c20a-1435393237.us-east-1.elb.amazonaws.com)
# NOTE: The IP changes when the Service is deleted and recreated (need to update DNS).
#

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-proxy
  labels:
    app: traefik-proxy
    tier: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-proxy
      tier: proxy
  template:
    metadata:
      labels:
        app: traefik-proxy
        tier: proxy
    spec:
      terminationGracePeriodSeconds: 60

      # kubectl create configmap traefik-conf --from-file=./conf/k8s/traefik.toml
      volumes:
      - name: config
        configMap:
          name: traefik-conf

      containers:
      - image: traefik:v1.2.0-rc1-alpine
        name: traefik-proxy
        resources:
          limits:
            cpu: "200m"
            memory: "30Mi"
          requests:
            cpu: "100m"
            memory: "20Mi"
        volumeMounts:
        - mountPath: "/conf"
          name: config
        ports:
        - containerPort: 80
          hostPort: 80
          name: traefik-proxy
        - containerPort: 8080
          name: traefik-ui
        args:
        - --configfile=/conf/traefik.toml
        - --kubernetes
        - --web

---

apiVersion: v1
kind: Service
metadata:
  name: traefik-proxy
  annotations:
    # SSL certificate.
    # https://console.aws.amazon.com/acm (alienlabs.io)
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:861694698401:certificate/28204a9f-69ec-424d-8f56-ac085b7bdad8"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: traefik-proxy
    tier: proxy
  ports:
  - port: 443
    targetPort: 80

---

#
# kubectl port-forward $(kubectl get pods | grep traefik-proxy | awk -F' ' '{print $1}') 8080:8080
#

apiVersion: v1
apiVersion: v1
kind: Service
metadata:
  name: traefik-ui
spec:
  selector:
    app: traefik-proxy
    tier: proxy
  ports:
  - port: 80
    targetPort: 8080
